name: shamra_app
description: "Shamra Electronics Mobile App - Browse and order electronics"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:

    sdk: flutter
  # Google Map
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  # State Management
  get: ^4.6.6
  change_app_package_name: ^1.1.0
  # HTTP Client
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1

  # Local Storage
  get_storage: ^2.1.1

  # UI Components
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0

  # Utils
  intl: ^0.20.2
  share_plus: ^12.0.0
  flutter_launcher_icons: ^0.14.4
  firebase_core: ^4.1.1
  firebase_messaging:
  url_launcher: ^6.2.1
  android_intent_plus: ^6.0.0
  intl_phone_field: ^3.2.0
  phone_numbers_parser: ^9.0.15
  photo_view: ^0.15.0
  image_picker: ^1.0.7
  font_awesome_flutter: ^10.11.0
  material_symbols_icons: ^4.2874.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/shamra_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
